[metadata]
addr = 4196125
size = 184
last_change = 1647472441

[header]
last_change = 1647472365
name = "mahaloz_main"
addr = 4196125

[stack_vars.-28]
last_change = 1647472441
stack_offset = -40
stack_offset_type = 1
name = "special_stack_var"
type = "char[16]"
size = 16
addr = 4196125
