[metadata]
addr = 4196125
size = 184
last_change = 1649620256

[header]
name = "mahaloz_main"
addr = 4196125

[stack_vars.-28]
stack_offset = -40
stack_offset_type = 1
name = "special_stack_var"
type = "char[16]"
size = 16
addr = 4196125
