[metadata]
addr = 4196125
size = 184
last_change = 1649620256

[header]
name = "mahaloz_main"
addr = 4196125

[stack_vars.-28]
stack_offset = -40
stack_offset_type = 1
name = "v5"
type = "char[16]"
size = 16
addr = 4196125

[stack_vars.-18]
stack_offset = -24
stack_offset_type = 1
name = "username"
type = "char[16]"
size = 16
addr = 4196125

[stack_vars.-2c]
stack_offset = -44
stack_offset_type = 1
name = "buf"
type = "int"
size = 4
addr = 4196125
