[metadata]
addr = 4196125
size = 184
last_change = 1661866204

[header]
last_change = 1661866204
name = "main_4"
addr = 4196125

[stack_vars.-28]
last_change = 1661533453
stack_offset = -40
stack_offset_type = 1
name = "erik_20"
type = "char[16]"
size = 16
addr = 4196125

[stack_vars.-18]
last_change = 1647472468
stack_offset = -24
stack_offset_type = 1
name = "username"
type = "char[16]"
size = 16
addr = 4196125

[stack_vars.-2c]
last_change = 1647472475
stack_offset = -44
stack_offset_type = 1
name = "buf"
type = "int"
size = 4
addr = 4196125
